### ISSUE TITLE
ng2-redux vs ngrx

### ISSUE THREAD

**Issue by iqmeta** [hendrikswan/pluralsight-angular-redux#2]
Hi,
very nice work, code looks pretty straight forward. I have two questions on your course.

1) Did you test also ngrx/store? 
I understand the differences (https://github.com/ngrx/store/issues/169), but 
you didn't mention it on your Pluralsight course page https://www.pluralsight.com/courses/angular-2-redux-manage-state, that there other commonly used libs doing almost the same? 
On purpose? Less benefits, or problems with it?

2) Server Stuff
On the course overview, I'm missing bit the part - how to preserve/track states on server side (cloud/multi devices/mobile+offline in mind)?
Are there any hooks, adapters, concepts, best practices to do so with redux?
As far I understand everything is by default stored to the localStorage of the browser (Press F5 ;-)  right? Are there any sync mechanisms or at least interfaces to get data stores merged with the server?

Thanks and greetings

**Comment by hendrikswan** [comment]
Hi! Thanks for the issue, and sorry that I've taken so long to get back to you. 
Here are my answers to your questions/concerns: 

1. I wanted to teach you the concepts of redux without using angular, then introduce redux to an existing angular app, before doing it in a more optimised way. So I didn't want to grab for a specific dependency right from the start, which I felt would be the case with ngrx/store. I could've mentioned it though! 

2. This depends heavily on the stack you are using. I wouldn't be surprised if there are libraries that sync between Redux and [insert server side stack here]. But redux is about client side state. Often used with pure REST to talk to the server. Also, by default, redux will only store in memory by default. If you want it to store to localstorage, you will need to use middleware for that. In a recent project of mine, I did sync between my redux store and the server, but I wrote totally custom code for that. It all depends on your architecture. 

I hope that helps!
